version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - cd fullstack-coding-challenge-this-is-yosuke/grocery-app
      - npm install
  pre_build:
    commands: 
      - npm run test:no-watch
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'fullstack-coding-challenge-this-is-yosuke/grocery-app/build'